[project]
name = "preprocessor"
version = "0.1.0"
description = "Benthic image preprocessor"
license = "Apache-2.0"
readme = "README.md"
authors = [
  { name = "Daniel A. A. Pelsmaeker", email = "developer@pelsmaeker.net" },
]
maintainers = [
  { name = "Daniel A. A. Pelsmaeker", email = "developer@pelsmaeker.net" },
]

requires-python = ">=3.12"
dependencies = []

[build-system]
requires = [
  "hatchling"
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
  "src/preprocessor"
]

[project.scripts]
preprocessor = "preprocessor.main:main"