[project]
name = "preprocessor"
version = "0.1.0"
description = "Benthic image preprocessor"
keywords = [ "preprocessor" ]

license = "Apache-2.0"
license-files = [ "LICENSE.md" ]
readme = "README.md"

authors = [
  { name = "Daniel A. A. Pelsmaeker", email = "developer@pelsmaeker.net" },
]
maintainers = [
  { name = "Daniel A. A. Pelsmaeker", email = "developer@pelsmaeker.net" },
]

requires-python = ">=3.12"
dependencies = []

[build-system]
requires = [ "hatchling", "hatch-vcs" ]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
# raw-options.root = ".."

[tool.hatch.build.hooks.vcs]
version-file = "src/preprocessor/_version.py"

[tool.hatch.build.targets.wheel]
packages = [
  "src/preprocessor"
]

[project.scripts]
preprocessor = "preprocessor.main:main"