[project]
dynamic = ["version", "urls"]

name = "preprocessor"
description = "Benthic image preprocessor"
keywords = ["preprocessor"]

license = "Apache-2.0"
license-files = ["LICENSE.md"]
readme = "README.md"

authors = [
  { name = "Daniel A. A. Pelsmaeker", email = "developer@pelsmaeker.net" },
]
maintainers = [
  { name = "Daniel A. A. Pelsmaeker", email = "developer@pelsmaeker.net" },
]

requires-python = ">=3.12,<4.0"
dependencies = [
  "click>=8.3.0",
  "opencv-contrib-python>=4.12.0.88",
  "pillow>=12.0.0",
  "pyside6>=6.10.0",
]
[dependency-groups]
dev = [
  "hatch>=1.15.1",
  "hatch-vcs>=0.5.0",
  "hatchling>=1.27.0",
  # For PyCharm 'Show as Image'
  "mypy>=1.18.2",
  "numpy>=2.2.6",
  "pillow>=12.0.0",
  "pyright>=1.1.406",
  "pytest>=8.4.2",
  "pytest-cov>=7.0.0",
  "ruff>=0.14.2",
  "yamlfix>=1.19.0",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/preprocessor/_version.py"

[tool.hatch.build.targets.wheel]
packages = [
  "src/preprocessor"
]

# See: https://packaging.python.org/en/latest/specifications/well-known-project-urls/#well-known-labels
[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://cambiomed-biodiversa.com/"
Source = "https://github.com/CAMBioMed/preprocessor/"
"Source Archive" = "https://github.com/CAMBioMed/preprocessor/archive/{commit_hash}.zip"

[project.scripts]
preprocessor = "preprocessor.main:cli"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = [
  "error",
]
log_cli_level = "INFO"
testpaths = [
  "tests",
]

[tool.coverage]
run.source = ["preprocessor"]
port.exclude_lines = [
  'pragma: no cover',
  '\.\.\.',
  'if typing.TYPE_CHECKING:',
]

[tool.ruff]
src = ["app"]
exclude = []
line-length = 120

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = [
  "YTT",         # flake8-2020
  "ANN",         # flake8-annotations
  "B",           # flake8-bugbear
  "C4",          # flake8-comprehensions
  "EM",          # flake8-errmsg
  "EXE",         # flake8-executable
  "ISC",         # flake8-implicit-str-concat
  "ICN",         # flake8-import-conventions
  "G",           # flake8-logging-format
  "PIE",         # flake8-pie
  "PT",          # flake8-pytest-style
  "RET",         # flake8-return
  "SIM",         # flake8-simplify
  "ARG",         # flake8-unused-arguments
  "I",           # isort
  "E", "W",      # pycodestyle
  "F",           # Pyflakes
  "D",           # pydocstyle
  "PGH",         # pygrep-hooks
  "PL",          # pylint
  "UP",          # pyupgrade
  "RUF",         # Ruff-specific
]
ignore = [
  "PLR",        # Pylint/Refactor
  "ISC001",     # flake8-implicit-str-concat - Conflicts with formatter
  "RET504",     # flake8-return - Unnecessary assignment to variable before `return` statement
  "D100",       # Allow missing docstrings
  "D101",       # Allow missing docstrings
  "D102",       # Allow missing docstrings
  "D103",       # Allow missing docstrings
  "D104",       # Allow missing docstrings
  "D105",       # Allow missing docstrings
  "D106",       # Allow missing docstrings
  "D107",       # Allow missing docstrings
  "D205",       # Conflicts with D202
]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
# Tests can ignore a few extra rules
"tests/**.py" = [
    "ANN201", # Missing return type annotation for public function
    "D103",   # Missing docstring
    "S101",   # Use of assert is detected
    "INP001", # Missing __init__.py file
]

[tool.yamlfix]
line_length = 120
sequence_style = "keep_style"
explicit_start = false
whitelines = 1
section_whitelines = 1
